@id=d66228d0-8663-4afe-9533-66df068781ca

PUT http://localhost:5113/workouts/{{id}}
Content-Type: application/json

{
    "name": "Arms",
    "description": "Arm workout",
    "startDateTime": "2023-04-08T08:00:00",
    "endDateTime": "2023-04-08T09:00:00",
    "exercises": [
        "Pull Ups",
        "Bench Press",
        "Lateral Raises"
    ]
}
